export const ALL_DATA_LOADED = "ALL_DATA_LOADED";

export const FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST'
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS'
export const FETCH_AUTH_FAILURE = 'FETCH_AUTH_FAILURE'

export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST'
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'

export const FETCH_CINEMAS_REQUEST = 'FETCH_CINEMAS_REQUEST'
export const FETCH_CINEMAS_SUCCESS = 'FETCH_CINEMAS_SUCCESS'
export const FETCH_CINEMAS_FAILURE = 'FETCH_CINEMAS_FAILURE'

export const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST'
export const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS'
export const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE'

export const FETCH_UPCOMING_REQUEST = 'FETCH_UPCOMING_REQUEST'
export const FETCH_UPCOMING_SUCCESS = 'FETCH_UPCOMING_SUCCESS'
export const FETCH_UPCOMING_FAILURE = 'FETCH_UPCOMING_FAILURE'

