const FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST'
const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS'
const FETCH_AUTH_FAILURE = 'FETCH_AUTH_FAILURE'

const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST'
const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS'
const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE'

const FETCH_CINEMAS_REQUEST = 'FETCH_CINEMAS_REQUEST'
const FETCH_CINEMAS_SUCCESS = 'FETCH_CINEMAS_SUCCESS'
const FETCH_CINEMAS_FAILURE = 'FETCH_CINEMAS_FAILURE'

const FETCH_GENRES_REQUEST = 'FETCH_GENRES_REQUEST'
const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS'
const FETCH_GENRES_FAILURE = 'FETCH_GENRES_FAILURE'

const FETCH_UPCOMING_REQUEST = 'FETCH_UPCOMING_REQUEST'
const FETCH_UPCOMING_SUCCESS = 'FETCH_UPCOMING_SUCCESS'
const FETCH_UPCOMING_FAILURE = 'FETCH_UPCOMING_FAILURE'

